= Pflichtenheft Dart-Scoring-App

== Ausgangssituation

Dart ist ein Spiel welches weltweit verbreitet ist.

== Istzustand

Viele Spieler spielen mit Dartscheiben, welche nicht
automatisch die Punkte abziehen.

== Problemstellung

Beim Dart spielen muessen die Spieler selbst die geworfenen
Punkte von ihrem momentan Punktestand abziehen, dabei koennen
bei komplizierten Rechnungen fehler entstehen.

== Sollzustand

Die Spieler sollen in einer App die geworfenen Punkte eingeben koennen
und diese werden dann automatisch abgezogen.

== Datenmodel

[plantuml, target=diagram-classes, format=png]
....
left to right direction

class Spiel{
    gameType: String
}

class Spieler{
    name: String
    id: Integer
    punkte: Integer
}

class Rechner{
    punkteErzielt: Integer
    momentanerSpieler: Integer
}


Spieler "*"--"1" Spiel : spielt >
Spieler "*"--"1" Rechner : benutzt >
....

Der Spieler hat einen Namen und eine Id um ihn zu identifizieren.

Der spieler spielt ein Spiel, dieses kann von 501 oder 301 Punkten starten.

Der Spieler benutzt den Rechner um seine erzielten Punkte einzutragen und von
seinen eigenen abzuziehen, im Rechner ist auch gespeichert welcher der Spieler
gerade dran ist, um die Punkte vom richtigen Spieler abzuziehen.

== Ziel

Die Spieler muessen nicht mehr im Kopf rechne und können sich
auf das Spiel konzentrieren, da keine Rechenfehler mehr
entstehen werden.