create table DSA_Player
(
    P_ID   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME   VARCHAR(20),
    PRIMARY KEY (P_ID)
);

create table DSA_GameType
(
    GT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    POINTS INTEGER,
    PRIMARY KEY(GT_ID)
);
create table DSA_Game
(
    G_ID           INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CURRENT_PLAYER INTEGER,
    GAME_TYPE_ID   INTEGER,
    PRIMARY KEY(G_ID),
    FOREIGN KEY (CURRENT_PLAYER) REFERENCES DSA_Player(P_ID),
    FOREIGN KEY (GAME_TYPE) REFERENCES DSA_Gametype(GT_ID)
);

create table DSA_GameParticipation(
    P_ID INTEGER,
    G_ID INTEGER,
    POINTS INTEGER,
    PRIMARY KEY(G_ID, P_ID)
);
