create table DSA_Player
(
    P_ID     INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME   VARCHAR,
    POINTS INTEGER
);

create table DSA_Gametype
(
    GT_ID        INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    GAME_TYPE VARCHAR
)
create table DSA_Game
(
    G_ID             INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    PLAYER_AMOUNT  INTEGER,
    CURRENT_PLAYER INTEGER,
    GAME_TYPE      INTEGER,
    CONSTRAINT     CURRENT_PLAYER REFERENCES DSA_Player (P_ID),
    CONSTRAINT     GAME_TYPE REFERENCES DSA_Gametype (GT_ID)
);
